# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Connie (Liangke) Gou
description: Homepage and Blogs of Connie Gou
brief-intro: Manager Statistics @ Abbvie 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gouliangke.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: LiangkeGou
facebook_username: 
github_username:  gouliangke
email: lgou@ucla.edu
weibo_username: 
zhihu_username: 
linkedIn_username: 
dribbble_username:

description_footer: Data scientist and biostatistician with life cycle drug development experiences (pre-clinical, clinical early and late phases) expanding multiple disease areas. Have over 3 years of experience for clinical trial data analysis, digital health data analysis, multi-omics data analysis and non-clinical statistics. Highly-skilled in machine learning, deep learning, statistical modeling, experimental design, causal inference, survival analysis, longitudinal analysis, advanced exploratory visualization and leadership.

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #hygblog
disqus_shortname: https-gouliangke-github-io

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
#baidu_tongji_id: cf8506e0ef223e57ff6239944e5d46a4
google_analytics_id: UA-124242346-1 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
#gems: [jekyll-paginate, jekyll-seo-tag]
gems: [jekyll-seo-tag]
#paginate: 6
#paginate_path: "blog/page:num/"


# For Jekyll-SEO
author:
  twitter: LiangkeGou
twitter:
  username: LiangkeGou
  card: summary
social:
  name: Liangke
  links:
    - https://twitter.com/Liangke
    - https://www.facebook.com/liangke.gou
    - https://www.linkedin.com/in/liangke-gou-9869907a/
    - https://github.com/gouliangke
    - https://www.youtube.com/channel/UC1scIK8-JKb9uKNwOSzwXFw/videos
    - https://zzjandglk.wordpress.com/
plugins:
    - jekyll-seo-tag